name: testing multiple branches
on:
  push: 
    branches: 
      - main 
      - develop 
jobs:
  develop:
    name: develop 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: display dev echo 
      id: dev
      run: |
        echo 'hello develop'

  
  main:
    name: main
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: display prod echo 
      id: prod
      run: |
        echo 'hello prod'